// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbtmsgrpeegctmmyutce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidG1zZ3JwZWVnY3RtbXl1dGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzQ1ODMsImV4cCI6MjA2OTkxMDU4M30.qMN2PpxNgonQxtNR37me_QItly3UEy5pb3BRCYYvAYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});